import sys

import users.usermanager


class User():

    user_count: int = 0
    firstname: str
    id_number: int

    def __init__(self, firstname: str, id_number: int = None):
        """
        Initializes a new user.
        :param firstname:   firstname of user
        :param id_number:   personalized id for each user, if not existent next id is generated by getting the current
                            user amount and increased by 1
        """
        self.firstname = firstname
        if id_number:
            self.id_number = id_number
        else:
            self.id_number = User.user_count
        User.user_count += 1
        users.usermanager.Usermanager.user_list.append(self)

    def __str__(self):
        ret = self.firstname + ', ' + str(self.id_number)
        return ret


def add_user(firstname):
    new_user = User(firstname, get_next_id())
    return new_user
    print("User angelegt")


def get_next_id():
    """
    :return: next available id based on number of added users
    """
    next_id = User.user_count
    User.user_count += 1
    return next_id